import re

class LaTeXSanitizer:
    """
    Cleans raw Markdown/LaTeX generated by VLM OCR models.
    Strips bounding box tags, normalizes math environments, and cleans formatting.
    """
    
    # Bounding box pattern (e.g. <|det|> or OmniDocBench tokens)
    DET_TOKEN_REGEX = re.compile(r"<\|det\|>|\<box\>.*?\</box\>", re.IGNORECASE)
    
    # Normalize display math \[ ... \] -> $$ ... $$
    DISPLAY_MATH_REGEX = re.compile(r"\\\[(.*?)\\\]", re.DOTALL)
    
    # Normalize inline math \( ... \) -> $ ... $
    INLINE_MATH_REGEX = re.compile(r"\\\((.*?)\\\)")

    @classmethod
    def sanitize(cls, raw_text: str) -> str:
        """
        Sanitizes raw VLM OCR output text.
        """
        if not raw_text:
            return ""

        # 1. Remove OCR detection tokens
        cleaned = cls.DET_TOKEN_REGEX.sub("", raw_text)

        # 2. Normalize display math delimiters
        cleaned = cls.DISPLAY_MATH_REGEX.sub(r"\n$$\n\1\n$$\n", cleaned)

        # 3. Normalize inline math delimiters
        cleaned = cls.INLINE_MATH_REGEX.sub(r"$\1$", cleaned)

        # 4. Clean up multiple empty lines (3 or more -> 2)
        cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)

        return cleaned.strip()
